# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/A7T100_Vivado/A7T100_Vivado.srcs/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1.xci
# IP: The module: 'Ece253_BlockDesign_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/A7T100_Vivado/A7T100_Vivado.gen/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ece253_BlockDesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/parallels/A7T100_Vivado/A7T100_Vivado.gen/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ece253_BlockDesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/parallels/A7T100_Vivado/A7T100_Vivado.gen/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ece253_BlockDesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/parallels/A7T100_Vivado/A7T100_Vivado.srcs/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1.xci
# IP: The module: 'Ece253_BlockDesign_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/A7T100_Vivado/A7T100_Vivado.gen/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ece253_BlockDesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/parallels/A7T100_Vivado/A7T100_Vivado.gen/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ece253_BlockDesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/parallels/A7T100_Vivado/A7T100_Vivado.gen/sources_1/bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ece253_BlockDesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
