# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab_files_2024/Nexys4_Handout_2022.xdc

# Block Designs: bd/Ece253_BlockDesign/Ece253_BlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign || ORIG_REF_NAME==Ece253_BlockDesign} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_mig_7series_0_0/Ece253_BlockDesign_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_mig_7series_0_0 || ORIG_REF_NAME==Ece253_BlockDesign_mig_7series_0_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_microblaze_0_0/Ece253_BlockDesign_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_microblaze_0_0 || ORIG_REF_NAME==Ece253_BlockDesign_microblaze_0_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_dlmb_v10_0/Ece253_BlockDesign_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_dlmb_v10_0 || ORIG_REF_NAME==Ece253_BlockDesign_dlmb_v10_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_ilmb_v10_0/Ece253_BlockDesign_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_ilmb_v10_0 || ORIG_REF_NAME==Ece253_BlockDesign_ilmb_v10_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_dlmb_bram_if_cntlr_0/Ece253_BlockDesign_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Ece253_BlockDesign_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_ilmb_bram_if_cntlr_0/Ece253_BlockDesign_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Ece253_BlockDesign_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_lmb_bram_0/Ece253_BlockDesign_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_lmb_bram_0 || ORIG_REF_NAME==Ece253_BlockDesign_lmb_bram_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_xbar_0/Ece253_BlockDesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_xbar_0 || ORIG_REF_NAME==Ece253_BlockDesign_xbar_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_microblaze_0_axi_periph_0/Ece253_BlockDesign_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Ece253_BlockDesign_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_microblaze_0_axi_intc_0/Ece253_BlockDesign_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Ece253_BlockDesign_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_microblaze_0_xlconcat_0/Ece253_BlockDesign_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Ece253_BlockDesign_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_mdm_1_0/Ece253_BlockDesign_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_mdm_1_0 || ORIG_REF_NAME==Ece253_BlockDesign_mdm_1_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_rst_mig_7series_0_100M_0/Ece253_BlockDesign_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==Ece253_BlockDesign_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_smartconnect_0_1/Ece253_BlockDesign_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_smartconnect_0_1 || ORIG_REF_NAME==Ece253_BlockDesign_smartconnect_0_1} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_timer_0_0/Ece253_BlockDesign_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_timer_0_0 || ORIG_REF_NAME==Ece253_BlockDesign_axi_timer_0_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_timer_1_0/Ece253_BlockDesign_axi_timer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_timer_1_0 || ORIG_REF_NAME==Ece253_BlockDesign_axi_timer_1_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_gpio_0_0/Ece253_BlockDesign_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_gpio_0_0 || ORIG_REF_NAME==Ece253_BlockDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_gpio_0_1/Ece253_BlockDesign_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_gpio_0_1 || ORIG_REF_NAME==Ece253_BlockDesign_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_sevenSeg_0_0/Ece253_BlockDesign_sevenSeg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_sevenSeg_0_0 || ORIG_REF_NAME==Ece253_BlockDesign_sevenSeg_0_0} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_gpio_0_2/Ece253_BlockDesign_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_gpio_0_2 || ORIG_REF_NAME==Ece253_BlockDesign_axi_gpio_0_2} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_gpio_0_3/Ece253_BlockDesign_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_gpio_0_3 || ORIG_REF_NAME==Ece253_BlockDesign_axi_gpio_0_3} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_gpio_0_4/Ece253_BlockDesign_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_gpio_0_4 || ORIG_REF_NAME==Ece253_BlockDesign_axi_gpio_0_4} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_clk_wiz_0_1/Ece253_BlockDesign_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_clk_wiz_0_1 || ORIG_REF_NAME==Ece253_BlockDesign_clk_wiz_0_1} -quiet] -quiet

# IP: bd/Ece253_BlockDesign/ip/Ece253_BlockDesign_axi_quad_spi_0_0/Ece253_BlockDesign_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ece253_BlockDesign_axi_quad_spi_0_0 || ORIG_REF_NAME==Ece253_BlockDesign_axi_quad_spi_0_0} -quiet] -quiet

# XDC: /home/parallels/A7T100_Vivado/A7T100_Vivado.gen/sources_1/bd/Ece253_BlockDesign/Ece253_BlockDesign_ooc.xdc
